name: Log Update

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  update_log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update Log
      run: |
        timestamp=$(date +"%Y.%m.%d %H:%M")
        echo $timestamp >> log.txt
